[project]
name = "dark-patterns-tesina"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.10.1",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "annotated-types==0.7.0",
    "attrs==25.3.0",
    "blinker==1.9.0",
    "blis==0.7.11",
    "catalogue==2.0.10",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "cloudpathlib==0.21.1",
    "colorama==0.4.6",
    "confection==0.1.5",
    "cymem==2.0.11",
    "datasets==4.0.0",
    "dill==0.3.8",
    "es-core-news-lg",
    "es-core-news-md",
    "es-core-news-sm",
    "fastapi>=0.128.1",
    "filelock==3.19.1",
    "frozenlist==1.7.0",
    "fsspec==2025.3.0",
    "httpx>=0.28.1",
    "huggingface-hub==0.34.4",
    "idna==3.10",
    "iniconfig==2.1.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "joblib==1.5.2",
    "langcodes==3.5.0",
    "language-data==1.3.0",
    "marisa-trie==1.3.1",
    "markdown-it-py==4.0.0",
    "markupsafe==3.0.2",
    "matplotlib>=3.11.1",
    "mdurl==0.1.2",
    "mpmath==1.3.0",
    "multidict==6.6.4",
    "multiprocess==0.70.16",
    "murmurhash==1.0.13",
    "networkx==3.5",
    "numpy==1.26.4",
    "packaging==25.0",
    "pandas==2.3.2",
    "pluggy==1.6.0",
    "preshed==3.0.10",
    "propcache==0.3.2",
    "psutil==7.0.0",
    "pyarrow==21.0.0",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pydantic-settings>=2.14.2",
    "pygments==2.19.2",
    "pytest==8.4.1",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "regex==2025.9.1",
    "requests==2.32.5",
    "rich==14.1.0",
    "safetensors==0.6.2",
    "scikit-learn==1.8.0",
    "scipy==1.16.1",
    "shellingham==1.5.4",
    "six==1.17.0",
    "smart-open==7.3.0.post1",
    "spacy==3.7.5",
    "spacy-legacy==3.0.12",
    "spacy-loggers==1.0.5",
    "srsly==2.5.1",
    "structlog>=26.1.0",
    "sympy==1.14.0",
    "thinc==8.2.5",
    "threadpoolctl==3.6.0",
    "tokenizers==0.22.0",
    "torch==2.8.0",
    "tqdm==4.67.1",
    "transformers==4.56.0",
    "typer==0.16.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "urllib3==2.5.0",
    "uvicorn[standard]>=0.52.0",
    "wasabi==1.1.3",
    "weasel==0.4.1",
    "wordcloud>=1.9.6",
    "wrapt==1.17.3",
    "xxhash==3.5.0",
    "yarl==1.20.1",
]

[tool.uv.sources]
es-core-news-lg = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_lg-3.7.0/es_core_news_lg-3.7.0-py3-none-any.whl" }
es-core-news-md = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.7.0/es_core_news_md-3.7.0-py3-none-any.whl" }
es-core-news-sm = { url = "https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.7.0/es_core_news_sm-3.7.0-py3-none-any.whl" }
